services:
  - type: web
    name: ratelockr-api
    runtime: node
    plan: free
    rootDirectory: service
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
